version: '3.8'

services: 
  postgres: # we can have multiple services here like redis,etc.
    image: postgres:15
    container_name: school_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: school
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # persisdtent data
# Persistent volume, so data is not lost when container is removed
volumes:
  postgres_data: